[features]
seeds = false
skip-lint = false
[programs.localnet]
w7 = "ExyjeDqAnvh7civmJpKGwV4HtNSmP4xSDVM6nskARWYK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "devnet"
wallet = "/home/terry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
